name: Build board (custom)

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard: Found in kbd_firmware/keyboards/[keyboard_name]'
        required: false
        default: crkbd
        type: string
      revision:
        description: 'Revision: '
        required: false
        default: rev4_1/standard
        type: string
      keymaps:
        description: 'Keymaps: via or vial'
        required: false
        default: vial
        type: string

run-name: ${{ inputs.keyboard }}-${{ inputs.revision | sed 's/\//_/' }}-${{ inputs.keymaps }}

