name: Build board (custom)

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard: Found in kbd_firmware/keyboards/[keyboard_name]'
        required: false
        default: crkbd
        type: string
      revision:
        description: 'Revision: '
        required: false
        default: rev4_1/standard
        type: string
      keymaps:
        description: 'Keymaps: via or vial'
        required: false
        default: vial
        type: string

run-name: ${{ inputs.keyboard }}-${{ inputs.revision | sed 's/\//_/' }}-${{ inputs.keymaps }}

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ${{ github.workspace }}  # 设置全局工作目录为仓库根目录

    steps:
    - uses: actions/checkout@v4

